### ISSUE TITLE
Broken Gnip JSON - Message cannot be correctly parsed

### ISSUE THREAD

**Issue by felipeclopes** [rweald/gnip-stream#6]
Hello, I'm facing a problem in my gnip-stream, I'm not sure if it is a broken Gnip message or a broken parsing from the gnip-stream Gem.

There are some Twitter messages in my stream that contains the following content:

```
[...]
"language":
    {
      "value":"en"
    }
  }
}
\r
4094804938752/SqTZKEo8_normal.jpeg",
"summary":null,
"links":
[
  {
    "href":null,
    "rel":"me"
  }
],
"friendsCount":228,
[...]
```

So when I'm trying to parse this JSON it generates an error. I believe that there is an error in the [data_buffer.rb](https://github.com/rweald/gnip-stream/blob/master/lib/gnip-stream/data_buffer.rb) concatenation, can you help me troubleshoot?

**Comment by rweald** [comment]
I took a look and wasn't able to reproduce the problem using the test stream I setup. However, there is a chance that it could be that my test stream is just too small volume to trigger an issue. 

I no longer use Gnip professionally so my access to their service has become relatively limited. I'd be happy to give you commit access if you are using this gem in production.

**Comment by felipeclopes** [comment]
Finally I had time to debug this issue, and found out that this issue was happening when the chunk has two and a half or more activities on it.

The Regex was capturing on the first item, the first complete activity and the second one was capturing till the following \r

I could not figure out a Regex to capture properly, so I made a rewrite in the DataBuffer for Json.

**Comment by rweald** [comment]
@felipeclopes awesome thanks for getting to the bottom of that. Do you want to submit a PR with your fixes? 

As I said before I no longer have access to Gnip data as I have changed jobs. I am happy to give you full committer access if you are actively using this project.

**Comment by felipeclopes** [comment]
I already made this PR https://github.com/rweald/gnip-stream/pull/8 a few months ago. Please, could you take a look and review it before merging? If you have time of course. Otherwise, just accept it, that I'm using it in production already.

**Comment by felipeclopes** [comment]
Fixed in https://github.com/rweald/gnip-stream/pull/8
